#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Copy of `sft_trl_lora_qlora.ipynb` (refactored into a standalone UV +
Jobs-friendly script).

Automatically generated by Colab (original notebook):
    https://colab.research.google.com/drive/1zBD1SMybwQubBDs2CTls3I8aeWyL03fW

This version:
- Removes notebook-only cells (`!pip`, `notebook_login`, exploratory prints)
- Adds inline UV dependencies so you can run it with `hf jobs uv run ...`

Relevant docs:
- TRL Jobs Training: https://huggingface.co/docs/trl/en/jobs_training
- HF Hub Jobs guide: https://huggingface.co/docs/huggingface_hub/en/guides/jobs
"""

# pylint: disable=import-error

# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "torch",
#   "transformers==4.56.2",
#   "trl==0.22.2",
#   "datasets",
#   "peft",
#   "accelerate",
#   "trackio",
#   "sentencepiece",
#   "protobuf",
#   "numpy<2",
#   "python-dotenv",
# ]
# ///

from __future__ import annotations

import argparse
import os
import platform

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Disable MPS on macOS before importing torch to avoid dtype incompatibilities
if platform.system() == "Darwin":
    os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


def _env_default(name: str, default: Optional[str] = None) -> Optional[str]:
    v = os.environ.get(name)
    return v if v not in (None, "") else default


def _parse_bool(value: Optional[str]) -> bool:
    """Parse string to boolean."""
    if value is None:
        return False
    return value.lower() in ("true", "1", "yes")


@dataclass(frozen=True)
class TrainConfig:
    model_id: str
    dataset_name: str
    dataset_config: Optional[str]
    dataset_split: str
    output_dir: str
    hub_model_id: Optional[str]
    push_to_hub: bool
    max_steps: int
    learning_rate: float
    per_device_train_batch_size: int
    gradient_accumulation_steps: int
    warmup_steps: int
    max_length: int
    report_to: str
    trackio_space_id: Optional[str]
    use_liger_kernel: bool
    use_qlora: bool
    attn_implementation: str
    dtype: str
    seed: int


def parse_args() -> TrainConfig:
    p = argparse.ArgumentParser(
        description=(
            "SFT finetune (LoRA/QLoRA) for FunctionGemma using TRL, runnable "
            "as a standalone UV script (hf jobs uv run)."
        )
    )

    p.add_argument(
        "--model-id",
        default=_env_default("MODEL_ID", "google/functiongemma-270m-it"),
    )
    p.add_argument(
        "--dataset-name",
        default=_env_default("DATASET_NAME", "google/mobile-actions"),
    )
    p.add_argument(
        "--dataset-config",
        default=_env_default("DATASET_CONFIG", "default"),
    )
    p.add_argument(
        "--dataset-split",
        default=_env_default("DATASET_SPLIT", "train"),
    )

    p.add_argument(
        "--output-dir",
        default=_env_default("OUTPUT_DIR", "function-gemma"),
    )
    p.add_argument(
        "--push-to-hub",
        type=lambda x: x.lower() in ("true", "1", "yes"),
        default=_parse_bool(_env_default("PUSH_TO_HUB", "0")),
    )
    p.add_argument(
        "--hub-model-id",
        default=_env_default("HUB_MODEL_ID", None),
    )

    p.add_argument(
        "--max-steps",
        type=int,
        default=int(_env_default("MAX_STEPS", "30")),
    )
    p.add_argument(
        "--learning-rate",
        type=float,
        default=float(_env_default("LEARNING_RATE", "2e-4")),
    )
    p.add_argument(
        "--per-device-train-batch-size",
        type=int,
        default=int(_env_default("BATCH_SIZE", "1")),
    )
    p.add_argument(
        "--gradient-accumulation-steps",
        type=int,
        default=int(_env_default("GRAD_ACCUM", "4")),
    )
    p.add_argument(
        "--warmup-steps",
        type=int,
        default=int(_env_default("WARMUP_STEPS", "5")),
    )
    p.add_argument(
        "--max-length",
        type=int,
        default=int(_env_default("MAX_LENGTH", "1024")),
    )

    p.add_argument(
        "--report-to",
        default=_env_default("REPORT_TO", "none"),
        help="Comma-separated reporters (e.g. 'trackio', 'wandb') or 'none'.",
    )
    p.add_argument(
        "--trackio-space-id",
        default=_env_default("TRACKIO_SPACE_ID", None),
        help=(
            "Optional: HF Space id/name for Trackio. If unset, defaults to output_dir when report_to includes trackio."
        ),
    )
    p.add_argument(
        "--use-liger-kernel",
        type=lambda x: x.lower() in ("true", "1", "yes"),
        default=_parse_bool(_env_default("USE_LIGER", "0")),
    )

    p.add_argument(
        "--use-qlora",
        type=lambda x: x.lower() in ("true", "1", "yes"),
        default=_parse_bool(_env_default("USE_QLORA", "0")),
    )
    p.add_argument(
        "--attn-implementation",
        default=_env_default("ATTN_IMPL", "sdpa"),
    )
    p.add_argument(
        "--dtype",
        default=_env_default("DTYPE", "float32"),
        choices=["float16", "bfloat16", "float32"],
    )
    p.add_argument("--seed", type=int, default=int(_env_default("SEED", "42")))

    a = p.parse_args()
    return TrainConfig(
        model_id=a.model_id,
        dataset_name=a.dataset_name,
        dataset_config=a.dataset_config,
        dataset_split=a.dataset_split,
        output_dir=a.output_dir,
        hub_model_id=a.hub_model_id,
        push_to_hub=bool(a.push_to_hub),
        max_steps=a.max_steps,
        learning_rate=a.learning_rate,
        per_device_train_batch_size=a.per_device_train_batch_size,
        gradient_accumulation_steps=a.gradient_accumulation_steps,
        warmup_steps=a.warmup_steps,
        max_length=a.max_length,
        report_to=a.report_to,
        trackio_space_id=a.trackio_space_id,
        use_liger_kernel=bool(a.use_liger_kernel),
        use_qlora=bool(a.use_qlora),
        attn_implementation=a.attn_implementation,
        dtype=a.dtype,
        seed=a.seed,
    )


def _as_report_to_list(v: str) -> List[str]:
    v = v.strip()
    if v.lower() in ("none", "null", ""):
        return []
    return [x.strip() for x in v.split(",") if x.strip()]


def main() -> None:
    cfg = parse_args()

    # HF Jobs best practice: keep caches in writable workspace.
    os.environ.setdefault("HF_HOME", os.path.abspath("./.hf_home"))
    os.environ.setdefault(
        "TRANSFORMERS_CACHE",
        os.path.abspath("./.hf_home/transformers"),
    )
    os.environ.setdefault(
        "HF_DATASETS_CACHE",
        os.path.abspath("./.hf_home/datasets"),
    )

    import torch  # type: ignore[import-not-found]
    from datasets import load_dataset  # type: ignore[import-not-found]
    from peft import LoraConfig  # type: ignore[import-not-found]
    from transformers import (  # type: ignore[import-not-found]
        AutoModelForCausalLM,
        AutoTokenizer,
        BitsAndBytesConfig,
    )
    from trl import SFTConfig, SFTTrainer  # type: ignore[import-not-found]

    torch.manual_seed(cfg.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(cfg.seed)
        torch.backends.cuda.matmul.allow_tf32 = True

    torch_dtype = torch.float16 if cfg.dtype == "float16" else torch.bfloat16

    print(f"[config] model_id={cfg.model_id}")
    print(f"[config] dataset={cfg.dataset_name}/{cfg.dataset_config}:{cfg.dataset_split}")
    print(f"[config] output_dir={cfg.output_dir} push_to_hub={cfg.push_to_hub} hub_model_id={cfg.hub_model_id}")
    print(f"[config] use_qlora={cfg.use_qlora} dtype={cfg.dtype} attn={cfg.attn_implementation}")

    # Dataset (expects `messages` column).
    ds_kwargs: Dict[str, Any] = {"split": cfg.dataset_split}
    if cfg.dataset_config:
        train_dataset = load_dataset(
            cfg.dataset_name,
            cfg.dataset_config,
            **ds_kwargs,
        )
    else:
        train_dataset = load_dataset(cfg.dataset_name, **ds_kwargs)

    if "messages" not in train_dataset.column_names:
        raise ValueError(f"Dataset must have a 'messages' column. Found: {train_dataset.column_names}")

    # Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        cfg.model_id,
        trust_remote_code=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Format into `text` using the model's chat template.
    def _format_to_text(examples: Dict[str, Any]) -> Dict[str, Any]:
        convos = examples["messages"]
        texts = [
            tokenizer.apply_chat_template(
                convo,
                tokenize=False,
                add_generation_prompt=False,
            )
            for convo in convos
        ]
        return {"text": texts}

    train_dataset = train_dataset.map(
        _format_to_text,
        batched=True,
        remove_columns=[c for c in train_dataset.column_names if c != "messages"],
    )
    train_dataset = train_dataset.remove_columns(["messages"])

    quantization_config = None
    if cfg.use_qlora:
        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch_dtype,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
        )

    # Determine device (use CPU on macOS due to MPS limitations)
    import platform
    if platform.system() == "Darwin":
        device_map = "cpu"
    else:
        device_map = "auto"

    model = AutoModelForCausalLM.from_pretrained(
        cfg.model_id,
        attn_implementation=cfg.attn_implementation,
        use_cache=False,
        device_map="cpu" if platform.system() == "Darwin" else "auto",
        trust_remote_code=True,
        quantization_config=quantization_config,
        low_cpu_mem_usage=True,
    )

    # Convert model to target dtype, then device
    model = model.to(torch_dtype)
    if platform.system() != "Darwin":
        model = model.to(device_map)

    peft_config = LoraConfig(
        r=32,
        lora_alpha=32,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
    )

    report_to = _as_report_to_list(cfg.report_to)
    trackio_space_id = cfg.trackio_space_id
    if trackio_space_id is None and "trackio" in report_to:
        trackio_space_id = cfg.output_dir

    training_args = SFTConfig(
        per_device_train_batch_size=cfg.per_device_train_batch_size,
        gradient_accumulation_steps=cfg.gradient_accumulation_steps,
        warmup_steps=cfg.warmup_steps,
        max_steps=cfg.max_steps,
        learning_rate=cfg.learning_rate,
        optim="adamw_torch",
        logging_steps=1,
        report_to=report_to,
        output_dir=cfg.output_dir,
        max_length=cfg.max_length,
        use_liger_kernel=cfg.use_liger_kernel,
        activation_offloading=False,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        push_to_hub=cfg.push_to_hub,
        hub_model_id=cfg.hub_model_id,
        bf16=False,
        fp16=False,
    )

    # Ensure model stays on CPU for macOS compatibility
    if platform.system() == "Darwin":
        # Move model to CPU and convert all bfloat16 to float32 recursively
        model = model.cpu()
        
        def convert_to_float32(module):
            for child in module.children():
                convert_to_float32(child)
            # Convert parameters
            for name, param in module.named_parameters(recurse=False):
                if param.dtype == torch.bfloat16:
                    module.register_parameter(name, torch.nn.Parameter(param.float()))
            # Convert buffers
            for name, buf in module.named_buffers(recurse=False):
                if buf is not None and buf.dtype == torch.bfloat16:
                    module.register_buffer(name, buf.float())
        
        convert_to_float32(model)

    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        peft_config=peft_config,
        processing_class=tokenizer,
    )

    trainer.train()
    trainer.save_model(cfg.output_dir)
    tokenizer.save_pretrained(cfg.output_dir)

    if cfg.push_to_hub:
        print("[hub] pushing to hub...")
        trainer.push_to_hub()

    print("[done] training complete")


if __name__ == "__main__":
    main()